### ISSUE TITLE
How ignore Exception Connection Timeout 

### ISSUE THREAD

**Issue by lpcadev** [alexdebril/rss-atom-bundle#110]
Hi,
Maybe it's a doubt and not a inssue.
I'm using the reader in a loop, so, I need to ignore timeout errors.
How should I do this ?
I may have to override DriverUnreachableResourceException to ingore it.
I do not know if I'm correct.

Thanks

**Comment by alexdebril** [comment]
Hi,

Yes, just catch DriverUnreachableResourceException in your loop to skip the problem. However, don't forget to log it in order to keep track of unreliable feeds.

Alex

**Comment by lpcadev** [comment]
Ok. I will try.. Thanks.
