### ISSUE TITLE
Impossible to guess date format 

### ISSUE THREAD

**Issue by Medkhalil97** [alexdebril/rss-atom-bundle#111]
Impossible to guess date format : Mon, 25 Apr 2016 15:31:28 GMT

Exception: Impossible to guess date format

**Comment by alexdebril** [comment]
Hi,

Could you give me the feed's URL please ?

Alex

**Comment by Medkhalil97** [comment]
Here it is : [http://feeds.nytimes.com/nyt/rss/Technology](url)

**Comment by NoScopie** [comment]
I have the same issue for Thu, 11 Aug 2016 09:47 EDT (http://www.nasa.gov/rss/dyn/onthestation_rss.rss)
