### ISSUE TITLE
Handle other tags for items

### ISSUE THREAD

**Issue by Heshyo** [alexdebril/rss-atom-bundle#116]
The `ItemOutInterface` can get very specific tags, but what if I have others? Is there there a simple way to handle them?

**Comment by alexdebril** [comment]
Yes, using [ Debril\RssAtomBundle\Protocol\Parser::getMedias()](https://github.com/alexdebril/rss-atom-bundle/blob/master/Protocol/Parser/Item.php#L350) to get images and [ Debril\RssAtomBundle\Protocol\Parser::getAdditional()](https://github.com/alexdebril/rss-atom-bundle/blob/master/Protocol/Parser/Item.php#L326) for all other tags.

This part is not well documented, sorry for that.

**Comment by Heshyo** [comment]
Thanks. With my `$item` I'm already doing things like

```php
$item->getPublicId();
$item->getTitle());
$item->getDescription();
$item->getCategories()[0]->getName();
$item->getMedias()->current()->getUrl();
```
I tried `$item->getAdditional()` but it gives me an empty array, while I have an additional tag between `guid` and  `description`. Is this how I'm supposed to use it?

**Comment by alexdebril** [comment]
Yes, that's the way you're supposed to get additional tags. Can you give me the feed's link please ?

**Comment by Heshyo** [comment]
Thanks: http://www.rci.fm/mobile

**Comment by alexdebril** [comment]
I guess it's the 'chapo' tag, that's it ?

**Comment by Heshyo** [comment]
Yes it's the `chapo` tag.

**Comment by Heshyo** [comment]
I just read the code and it looks like you're using namespaces to get additional elements, while the feed I'm using doesn't have namespaces. So if the feed were correct, it would probably work, something like
```
$xmlElements = $item->getAdditional("myNamespace");
foreach ($xmlElements as $xmlElement) { ... }
```

**Comment by alexdebril** [comment]
Yes, and it can be too strict for your case.

Have you tried https://github.com/alexdebril/feed-io ? Additional tags are detected from the node tree not using the namespace.

**Comment by Heshyo** [comment]
Thanks Alex.

I tried https://github.com/alexdebril/feed-io . The API is almost the same, there were just a few things to adjust. What I don't understand though is why it can't read the public ID. I didn't fully read the source, I just noticed that if it can't get the ID, it returns the link instead. On https://github.com/alexdebril/rss-atom-bundle it reads it perfectly well. In some of my cases the link contains the ID, so I can just parse it.

```php
// /!\ getPublicId is not returning the ID from <guid isPermaLink="true">114237</guid>
// unlike with rss-atom-bundle. For some reason it can't get it and return the link instead.
$item->getPublicId();

$item->getTitle();
$item->getDescription();
$item->getCategories()[0]->getLabel();
$item->getMedias()[0]->getUrl();

// I can walk through all additional elements.
foreach ($item->getAllElements() as $additionalElement) {
	if ($additionalElement->getName("chapo")) {
		// do something ...
	} else { /* ... */ }
}

$item->getLastModified();
$item->getLink();
```

**Comment by alexdebril** [comment]
You're welcome.

Besides the publicId trouble, is the solution OK for you ?

**Comment by Heshyo** [comment]
Yes thanks, the code I posted is basically what I'm currently using and it does its job.

**Comment by alexdebril** [comment]
ok thanks
