### ISSUE TITLE
String could not be parsed as XML: Try to get utf-8 feeds from a remote service gut got A syntax error.

### ISSUE THREAD

**Issue by dassiorleando** [alexdebril/rss-atom-bundle#117]
When trying to get feeds probides by http://www.sportytrader.com/pronostic.xml I got String could not be parsed as XML.

Knowing that it is not really and issue, but I thinkg that it will be a good thing that the bundle also works with french feed, generally with UTF-8 syntax with accent on letters.

When get these feeds with this code I get a correct xml syntax without problems:

> $feed = implode(file($url));
>         $feed = utf8_encode($feed);
>         $logger->info($feed);
>         $xml = simplexml_load_string($feed);

`<?xml version="1.0" encoding="utf-8"?> <channel><title>Derniers pronos foot de SportyTrader</title><description>L'actualité des pronos foot de SportyTrader</description><link>http://www.sportytrader.com/pronostic.xml</link><item><pubDate>Sat, 13 Aug 2016 06:45:00 +0200</pubDate><title>Pronostic Chelsea - West Ham</title><link>http://www.sportytrader.com/pronostic-chelsea-west_ham-45324.htm</link><description>Pour sa première à la tête de Chelsea en match officiel, Antonio Conte battra-t-il le West Ham de Dimitri Payet</description><ligue>Premier League</ligue><matchDate>2016-08-15 21:00:00</matchDate></item><item><pubDate>Fri, 12 Aug 2016 12:30:00 +0200</pubDate><title>Pronostic Nice - Rennes</title><link>http://www.sportytrader.com/pronostic-nice-rennes-45314.htm</link><description>Dimanche à 17h, l'OGC Nice reçoit le Stade Rennais dans le cadre de la 1e journée de Ligue 1. Sans</description><ligue>Ligue 1</ligue><matchDate>2016-08-14 17:00:00</matchDate></item><item><pubDate>Fri, 12 Aug 2016 08:30:00 +0200</pubDate><title>Pronostic Dortmund - Bayern Munich</title><link>http://www.sportytrader.com/pronostic-dortmund-bayern-45310.htm</link><description>Le mercato de feu du Borussia Dortmund suffira-t-il à combler l'écart avec le Bayern Munich lors de cette Supercoupe d'Allemagne</description><ligue>Super Coupe d'Allemagne</ligue><matchDate>2016-08-14 20:30:00</matchDate></item><item><pubDate>Fri, 12 Aug 2016 08:00:00 +0200</pubDate><title>Pronostic Arsenal - Liverpool</title><link>http://www.sportytrader.com/pronostic-arsenal-liverpool-45309.htm</link><description>Gros choc dès la première journée ! Qui d'Arsenal ou Liverpool démarrera le mieux cette saison ? La Premier League</description><ligue>Premier League</ligue><matchDate>2016-08-14 17:00:00</matchDate></item><item><pubDate>Fri, 12 Aug 2016 07:00:00 +0200</pubDate><title>Pronostic Manchester City - Sunderland</title><link>http://www.sportytrader.com/pronostic-manchester_city-sunderland-45308.htm</link><description>Débuts de Pep Guardiola à la tête de Manchester City ! Formalité face à Sunderland, 17ème du précédent exercice ?</description><ligue>Premier League</ligue><matchDate>2016-08-13 18:30:00</matchDate></item><item><pubDate>Fri, 12 Aug 2016 06:30:00 +0200</pubDate><title>Pronostic Everton - Tottenham</title><link>http://www.sportytrader.com/pronostic-everton-tottenham-45307.htm</link><description>3ème la saison passée, Tottenham confirmera-t-il en allant s'imposer dès la 1ère journée à Everton ? La Premier League reprend</description><ligue>Premier League</ligue><matchDate>2016-08-13 16:00:00</matchDate></item><item><pubDate>Thu, 11 Aug 2016 17:00:00 +0200</pubDate><title>Pronostic Canada - France</title><link>http://www.sportytrader.com/pronostic-canada-france-45297.htm</link><description>Les Françaises affrontent la Colombie Samedi à minuit (h.f.) dans le cadre des quarts de finale du Tournoi Olympique.</description><ligue>Women</ligue><matchDate>2016-08-13 00:00:00</matchDate></item><item><pubDate>Thu, 11 Aug 2016 16:15:00 +0200</pubDate><title>Pronostic Metz - Lille</title><link>http://www.sportytrader.com/pronostic-metz-lille-45296.htm</link><description>Samedi à 20h00, le promu messin accueille le LOSC pour le compte de la 1e journée de Ligue 1. Après</description><ligue>Ligue 1</ligue><matchDate>2016-08-13 20:00:00</matchDate></item><item><pubDate>Thu, 11 Aug 2016 16:00:00 +0200</pubDate><title>Pronostic Dijon - Nantes</title><link>http://www.sportytrader.com/pronostic-dijon-nantes-45295.htm</link><description>Samedi à 20h00, le promu dijonnais reçoit le FC Nantes dans le cadre de la 1e journée de Ligue 1.</description><ligue>Ligue 1</ligue><matchDate>2016-08-13 20:00:00</matchDate></item><item><pubDate>Thu, 11 Aug 2016 15:30:00 +0200</pubDate><title>Pronostic Montpellier - Angers</title><link>http://www.sportytrader.com/pronostic-montpellier-angers-45293.htm</link><description>Comme la saison précédente, Angers se déplace ce samedi à Montpellier dès l'ouverture du championnat de Ligue 1. Le SCO</description><ligue>Ligue 1</ligue><matchDate>2016-08-13 20:00:00</matchDate></item><item><pubDate>Thu, 11 Aug 2016 06:45:00 +0200</pubDate><title>Pronostic Séville - Barcelone</title><link>http://www.sportytrader.com/pronostic-seville-barcelone-45279.htm</link><description>Nouveau choc en Espagne ! Après le Real Madrid, le FC Séville affronte Barcelone dans le cadre de la Supercoupe</description><ligue>Super Cup</ligue><matchDate>2016-08-14 22:00:00</matchDate></item><item><pubDate>Wed, 10 Aug 2016 17:00:00 +0200</pubDate><title>Pronostic Nîmes - Lens</title><link>http://www.sportytrader.com/pronostic-nimes-lens-45270.htm</link><description>Lundi à 20h30, le FC Nîmes accueille le Racing Club de Lens en clôture de la 3e journée de Ligue</description><ligue>Ligue 2</ligue><matchDate>2016-08-15 18:30:00</matchDate></item><item><pubDate>Wed, 10 Aug 2016 15:30:00 +0200</pubDate><title>Pronostic Valenciennes - Reims</title><link>http://www.sportytrader.com/pronostic-valenciennes-reims-45269.htm</link><description>Samedi à 15h, le Stade de Reims se déplace à Valenciennes pour le compte de la 3e journée de Ligue</description><ligue>Ligue 2</ligue><matchDate>2016-08-13 13:00:00</matchDate></item><item><pubDate>Wed, 10 Aug 2016 14:45:00 +0200</pubDate><title>Pronostic Clermont Foot - Sochaux</title><link>http://www.sportytrader.com/pronostic-clermont-sochaux-45268.htm</link><description>Vendredi, le Clermont Foot accueille le FC Sochaux dans le cadre de la 3e journée de Ligue 2. Après un</description><ligue>Ligue 2</ligue><matchDate>2016-08-12 18:00:00</matchDate></item><item><pubDate>Tue, 09 Aug 2016 16:45:00 +0200</pubDate><title>Pronostic New Zealand - France</title><link>http://www.sportytrader.com/pronostic-nouvelle_zelande-france-45245.htm</link><description>Mercredi à minuit (h.f.), l'équipe de France de football féminin affronte la Nouvelle-Zélande pour le compte de la 3e journée</description><ligue>Women</ligue><matchDate>2016-08-10 00:00:00</matchDate></item><item><pubDate>Tue, 09 Aug 2016 15:30:00 +0200</pubDate><title>Pronostic Nancy - Lyon</title><link>http://www.sportytrader.com/pronostic-nancy-lyon-45244.htm</link><description>Dimanche à 15h, l'OL de Jean Michel Aulas se déplace à Nancy pour le compte de la 1e journée de</description><ligue>Ligue 1</ligue><matchDate>2016-08-14 15:00:00</matchDate></item><item><pubDate>Tue, 09 Aug 2016 11:30:00 +0200</pubDate><title>Pronostic Caen - Lorient</title><link>http://www.sportytrader.com/pronostic-caen-lorient-45242.htm</link><description>Samedi à 20 h, Caen reçoit Lorient pour le compte de la 1ère journée de Ligue 1 édition 2016/17. Après</description><ligue>Ligue 1</ligue><matchDate>2016-08-13 20:00:00</matchDate></item><item><pubDate>Tue, 09 Aug 2016 10:30:00 +0200</pubDate><title>Pronostic Bordeaux - St Etienne</title><link>http://www.sportytrader.com/pronostic-bordeaux-saint_etienne-45239.htm</link><description>Samedi à 17h, Bordeaux reçoit l'ASSE dans le cadre de la 1ere journée de Ligue 1. Cantonnés au ventre mou</description><ligue>Ligue 1</ligue><matchDate>2016-08-13 17:00:00</matchDate></item><item><pubDate>Mon, 08 Aug 2016 15:45:00 +0200</pubDate><title>Pronostic Marseille - Toulouse</title><link>http://www.sportytrader.com/pronostic-om-toulouse-45227.htm</link><description>Dimanche, l'OM reçoit le TFC en clôture de la 1e journée de L1. Après un mercato mouvementé, Marseille va-t-il retrouver</description><ligue>Ligue 1</ligue><matchDate>2016-08-14 20:45:00</matchDate></item><item><pubDate>Mon, 08 Aug 2016 11:45:00 +0200</pubDate><title>Pronostic Monaco - Guingamp</title><link>http://www.sportytrader.com/pronostic-monaco-guingamp-45226.htm</link><description>Vendredi, Guingamp se rend sur le Rocher pour affronter Monaco dans le cadre de la 1ere journée de Ligue 1.</description><ligue>Ligue 1</ligue><matchDate>2016-08-12 20:30:00</matchDate></item><item><pubDate>Mon, 08 Aug 2016 10:30:00 +0200</pubDate><title>Pronostic Bastia - PSG</title><link>http://www.sportytrader.com/pronostic-bastia-psg-45225.htm</link><description>Vendredi, Paris se déplace à Bastia en ouverture de la première journée du championnat de Ligue 1. Après sa victoire</description><ligue>Ligue 1</ligue><matchDate>2016-08-12 20:00:00</matchDate></item><item><pubDate>Sat, 06 Aug 2016 23:30:00 +0200</pubDate><title>Pronostic Real Madrid - Séville</title><link>http://www.sportytrader.com/pronostic-real_madrid-seville-45193.htm</link><description>Duel 100% espagnol pour cette Supercoupe d'Europe ! Qui du Real, vainqueur de la LDC, ou de Séville, à nouveau</description><ligue>Super Cup</ligue><matchDate>2016-08-09 20:45:00</matchDate></item><item><pubDate>Thu, 04 Aug 2016 17:15:00 +0200</pubDate><title>Pronostic Leicester - Manchester United</title><link>http://www.sportytrader.com/pronostic-leicester-manchester_united-45170.htm</link><description>Premier match de la saison anglaise : Leicester, champion en titre, confirmera-t-il sa saison exceptionnelle en venant à bout du</description><ligue>Community Shield</ligue><matchDate>2016-08-07 17:00:00</matchDate></item><item><pubDate>Thu, 04 Aug 2016 16:45:00 +0200</pubDate><title>Pronostic Sparta Rotterdam - Ajax</title><link>http://www.sportytrader.com/pronostic-sparta-ajax-45171.htm</link><description>Après le PSV, entrée en lice de son dauphin, l'Ajax Amsterdam ! Les Amstellodamois assureront-ils l'essentiel face au promu, le</description><ligue>Eredivisie</ligue><matchDate>2016-08-07 14:30:00</matchDate></item><item><pubDate>Thu, 04 Aug 2016 10:00:00 +0200</pubDate><title>Pronostic Mexique - Allemagne</title><link>http://www.sportytrader.com/pronostic-mexique-allemagne-45187.htm</link><description>Pour cette première journée du tournoi de football olympique masculin, le Mexique et l'Allemagne s'affrontent jeudi à 22 h (h.f.).</description><ligue>Men</ligue><matchDate>2016-08-04 22:00:00</matchDate></item><item><pubDate>Wed, 03 Aug 2016 18:45:00 +0200</pubDate><title>Pronostic Utrecht - PSV Eindhoven</title><link>http://www.sportytrader.com/pronostic-utrecht-psv-45169.htm</link><description>Après sa victoire lors de la Super Coupe face au Feyenoord, le PSV démarrera-t-il son championnat de la meilleure des</description><ligue>Eredivisie</ligue><matchDate>2016-08-06 17:45:00</matchDate></item><item><pubDate>Wed, 03 Aug 2016 18:30:00 +0200</pubDate><title>Pronostic PSG - Lyon</title><link>http://www.sportytrader.com/pronostic-psg-lyon-45168.htm</link><description>Premier match officiel pour Unai Emery à la tête du PSG ! Et première victoire ? Comme on se retrouve</description><ligue>Trophee des Champions</ligue><matchDate>2016-08-06 20:45:00</matchDate></item><item><pubDate>Wed, 03 Aug 2016 16:45:00 +0200</pubDate><title>Pronostic Portugal - Argentine</title><link>http://www.sportytrader.com/pronostic-portugal-argentine-45166.htm</link><description>Considérés parmi les favoris de l'épreuve, le Portugal et l'Argentine s'affrontent ce jeudi à 23h (h.f.) pour le compte de</description><ligue>Men</ligue><matchDate>2016-08-04 23:00:00</matchDate></item><item><pubDate>Wed, 03 Aug 2016 15:00:00 +0200</pubDate><title>Pronostic Racing Strasbourg - Amiens</title><link>http://www.sportytrader.com/pronostic-strasbourg-amiens-45164.htm</link><description>Samedi, Strasbourg accueille Amiens en clôture de la 2e journée de Ligue 2. Lequel de ces deux promus de National</description><ligue>Ligue 2</ligue><matchDate>2016-08-06 13:00:00</matchDate></item><item><pubDate>Wed, 03 Aug 2016 12:00:00 +0200</pubDate><title>Pronostic France - Colombie</title><link>http://www.sportytrader.com/pronostic-france-colombie-45165.htm</link><description>Pour leur premier match aux Jeux Olympiques de Rio, les Françaises affrontent la Colombie jeudi matin à 3h00 (h.f.). Les</description><ligue>Women</ligue><matchDate>2016-08-04 03:00:00</matchDate></item><item><pubDate>Tue, 02 Aug 2016 16:45:00 +0200</pubDate><title>Pronostic Sochaux - Valenciennes</title><link>http://www.sportytrader.com/pronostic-sochaux-valenciennes-45151.htm</link><description>Dans le cadre de la 2e journée de Ligue 2, Valenciennes se déplace à Sochaux ce vendredi. Les deux équipes</description><ligue>Ligue 2</ligue><matchDate>2016-08-05 20:00:00</matchDate></item><item><pubDate>Tue, 02 Aug 2016 16:00:00 +0200</pubDate><title>Pronostic Auxerre - GFCO Ajaccio</title><link>http://www.sportytrader.com/pronostic-gazelec_ajaccio-auxerre-45148.htm</link><description>Pour le compte de la 2e journée de Ligue 2, Auxerre accueille le Gazélec Ajaccio ce vendredi. Les deux équipes</description><ligue>Ligue 2</ligue><matchDate>2016-08-05 20:00:00</matchDate></item><item><pubDate>Tue, 02 Aug 2016 15:15:00 +0200</pubDate><title>Pronostic Lens - Tours</title><link>http://www.sportytrader.com/pronostic-lens-tours-45146.htm</link><description>Vendredi, Lens reçoit Tours pour le compte de la 2e journée de Ligue 2. Pour sa première de la saison</description><ligue>Ligue 2</ligue><matchDate>2016-08-05 20:00:00</matchDate></item><item><pubDate>Mon, 01 Aug 2016 17:00:00 +0200</pubDate><title>Pronostic Aek Athens - St Etienne</title><link>http://www.sportytrader.com/pronostic-athenes-saint_etienne-45124.htm</link><description>Après un spectacle affligeant à Geoffroy Guichard, Saint-Etienne a préservé l'essentiel en ne concédant aucun but contre l'AEK Athènes (0-0).</description><ligue>Europa Ligue</ligue><matchDate>2016-08-04 18:00:00</matchDate></item><item><pubDate>Mon, 01 Aug 2016 16:00:00 +0200</pubDate><title>Pronostic FK Qabala - Lille</title><link>http://www.sportytrader.com/pronostic-qabala-lille-45123.htm</link><description>Tenu en échec à domicile (1-1) contre la modeste équipe de Qabala lors du match aller du 3e tour préliminaire</description><ligue>Europa Ligue</ligue><matchDate>2016-08-04 19:00:00</matchDate></item><item><pubDate>Fri, 29 Jul 2016 14:15:00 +0200</pubDate><title>Pronostic Young Boys - Shakhtar Donetsk</title><link>http://www.sportytrader.com/pronostic-young_boys-shakhtar_donetsk-45088.htm</link><description>Le Young Boys de Berne accueille le Shakhtar Donetsk pour le match retour du 3e tour préliminaire de la Ligue</description><ligue>Ligue des Champions</ligue><matchDate>2016-08-03 20:15:00</matchDate></item><item><pubDate>Fri, 29 Jul 2016 12:00:00 +0200</pubDate><title>Pronostic Anderlecht - Rostov</title><link>http://www.sportytrader.com/pronostic-anderlecht-rostov-45084.htm</link><description>Anderlecht reçoit Rostov dans le cadre du match retour du 3e tour préliminaire de la Ligue des Champions. Après le</description><ligue>Ligue des Champions</ligue><matchDate>2016-08-03 18:45:00</matchDate></item><item><pubDate>Fri, 29 Jul 2016 10:15:00 +0200</pubDate><title>Pronostic Monaco - Fenerbahce</title><link>http://www.sportytrader.com/pronostic-monaco-fenerbahce-45078.htm</link><description>Battus 2-1 à Fenerbahce lors du match aller du troisième tour préliminaire de la Ligue des Champions, les Monégasques parviendront-ils</description><ligue>Ligue des Champions</ligue><matchDate>2016-08-03 20:45:00</matchDate></item><item><pubDate>Thu, 28 Jul 2016 14:30:00 +0200</pubDate><title>Pronostic Amiens - Reims</title><link>http://www.sportytrader.com/pronostic-amiens-reims-45055.htm</link><description>Rétrogradé en Ligue 2 la saison passée, Reims se déplace au Stade de la Licorne dans le cadre de la</description><ligue>Ligue 2</ligue><matchDate>2016-07-29 18:00:00</matchDate></item><item><pubDate>Wed, 27 Jul 2016 16:45:00 +0200</pubDate><title>Pronostic Red Star 93 - Auxerre</title><link>http://www.sportytrader.com/pronostic-red_star-auxerre-45044.htm</link><description>Samedi, le Red Star accueille Auxerre pour son premier match officiel au stade Jean Bouin. Longtemps à la lutte pour</description><ligue>Ligue 2</ligue><matchDate>2016-07-30 15:00:00</matchDate></item><item><pubDate>Tue, 26 Jul 2016 17:00:00 +0200</pubDate><title>Pronostic Valenciennes - Clermont Foot</title><link>http://www.sportytrader.com/pronostic-valenciennes-clermont-45026.htm</link><description>Vendredi, Valenciennes accueille Clermont dans le cadre de la 1e journée de Ligue 2. Les Nordistes vont-ils faire douter des</description><ligue>Ligue 2</ligue><matchDate>2016-07-29 20:00:00</matchDate></item><item><pubDate>Tue, 26 Jul 2016 16:30:00 +0200</pubDate><title>Pronostic Troyes - Sochaux</title><link>http://www.sportytrader.com/pronostic-troyes-sochaux-45024.htm</link><description>Troyes reçoit Sochaux ce vendredi pour le compte de la 1e journée de Ligue 2. Après une saison épouvantable en</description><ligue>Ligue 2</ligue><matchDate>2016-07-29 20:00:00</matchDate></item><item><pubDate>Tue, 26 Jul 2016 15:30:00 +0200</pubDate><title>Pronostic Niort - Lens</title><link>http://www.sportytrader.com/pronostic-niort-lens-45019.htm</link><description>Vendredi, le Racing club de Lens se rend à Niort dans le cadre de la 1e journée de Ligue 2.</description><ligue>Ligue 2</ligue><matchDate>2016-07-29 20:00:00</matchDate></item><item><pubDate>Tue, 26 Jul 2016 10:15:00 +0200</pubDate><title>Pronostic Shakhtar Donetsk - Young Boys</title><link>http://www.sportytrader.com/pronostic-shakhtar_donetsk-young_boys-45014.htm</link><description>Eliminés dès le tour préliminaire de la Ligue des Champions par Monaco la saison passée, les Young Boys de Berne</description><ligue>Ligue des Champions</ligue><matchDate>2016-07-26 20:45:00</matchDate></item><item><pubDate>Tue, 26 Jul 2016 09:30:00 +0200</pubDate><title>Pronostic Rostov - Anderlecht</title><link>http://www.sportytrader.com/pronostic-rostov-anderlecht-45013.htm</link><description>Mardi, Anderlecht affronte Rostov dans le cadre du 3e tour préliminaire de la Ligue des Champions. Les Belges vont-ils ramener</description><ligue>Ligue des Champions</ligue><matchDate>2016-07-26 20:30:00</matchDate></item><item><pubDate>Mon, 25 Jul 2016 16:00:00 +0200</pubDate><title>Pronostic St Etienne - Aek Athens</title><link>http://www.sportytrader.com/pronostic-saint_etienne-athenes-44992.htm</link><description>Éliminé en seizième de finale de la Ligue Europa la saison passée, l'ASSE a l'occasion de vivre une nouvelle épopée</description><ligue>Europa Ligue</ligue><matchDate>2016-07-28 21:00:00</matchDate></item><item><pubDate>Mon, 25 Jul 2016 14:45:00 +0200</pubDate><title>Pronostic Lille - FK Qabala</title><link>http://www.sportytrader.com/pronostic-lille-qabala-44989.htm</link><description>Après deux ans d'absence en compétition européenne, Lille accueille les Azéris du FK Qabala pour le 3e tour de la</description><ligue>Europa Ligue</ligue><matchDate>2016-07-28 19:00:00</matchDate></item><item><pubDate>Mon, 25 Jul 2016 09:45:00 +0200</pubDate><title>Pronostic Fenerbahce - Monaco</title><link>http://www.sportytrader.com/pronostic-fenerbahce-monaco-44985.htm</link><description>De retour en Ligue des Champions, Monaco se déplace à Fenerbahce dans l'espoir d'atteindre les phases de poules. Les joueurs</description><ligue>Ligue des Champions</ligue><matchDate>2016-07-27 20:30:00</matchDate></item></channel>`

But with the bundle I got errors.
Please need help with this.

**Comment by alexdebril** [comment]
The issue comes from the feed : https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.sportytrader.com%2Fpronostic.xml

> Your feed appears to be encoded as "utf-8", but your server is reporting "iso-8859-1"

I'll see what I can do to override the encoding.

**Comment by alexdebril** [comment]
Encoding issues are really unusual by now and besides this stream is not a feed.
