### ISSUE TITLE
Adding custom headers to the RSS HTTP request

### ISSUE THREAD

**Issue by nicorsm** [alexdebril/rss-atom-bundle#120]
I need to append a custom header to the HTTP Request of a Wordpress RSS feed.  The header I need is `Accept-Encoding: gzip, deflate`. 
I have a particular case of a blog which requires this header in order to get the "standard" Wordpress RSS feed. Otherwise, the HTTP request is redirected to FeedBurner which truncates the content tag of the feed.
Is there any way to add this header?
Thanks

**Comment by alexdebril** [comment]
Hi,

Do you mean like this ? https://github.com/alexdebril/rss-atom-bundle/commit/cbd5e730661b79cd6b5f7588b2685d64e036270f

**Comment by nicorsm** [comment]
Yes! That's what I needed. I used `curl_setopt($curl, CURLOPT_ENCODING, 'gzip, deflate');` instead. Thanks!!
