### ISSUE TITLE
Issue With Logger

### ISSUE THREAD

**Issue by bshoemaker136** [alexdebril/rss-atom-bundle#127]
In your extension class you have this:

$this->setDefinition($container, 'logger', 'Psr\Log\NullLogger');

Isn't that overriding the typical Monolog logger that has been provided by Symfony?  Is there a reason to override that?

**Comment by alexdebril** [comment]
Hi,

It's not overriding the default logger because `setDefinition` checks if the definition exists or has an alias before : 

```php
    protected function setDefinition(ContainerBuilder $container, $serviceName, $className)
    {
        if ( ! $container->hasDefinition($serviceName) && ! $container->hasAlias($serviceName)) {
            $container->setDefinition($serviceName, new Definition($className));
        }

        return $this;
    }
```
It creates a logger instance if your dependency injection doesn't have one, which is the case during the unit tests execution.

Do you experience an issue with that ?

**Comment by matteogatti** [comment]
After the upgrade form version 2.x to 3.0.4 the service **logger** was substituted from **Symfony\Bridge\Monolog\Logger** to **Psr\Log\NullLogger**. Strangely **$container->getDefinitions()** method gets an empty array and the **setDefinition** doesn't work properly. Maybe **setDefinition** needs some extra control.

**Comment by DonCallisto** [comment]
Same here.
It seems that `hasDefinition` and `hasAlias` will return both `false` (maybe container isn't processed yet?) and, so, definition gets and override.

**Comment by DonCallisto** [comment]
I've open a PR for this issue --> https://github.com/alexdebril/rss-atom-bundle/pull/128
Seems to work in my local application.

**Comment by alexdebril** [comment]
Thank you @DonCallisto , it works fine with the demo application. :+1:

**Comment by DonCallisto** [comment]
@alexdebril you're welcome. Maybe that's perfect for a patch version like 3.0.5. What do you think?

**Comment by alexdebril** [comment]
I just did it : https://github.com/alexdebril/rss-atom-bundle/releases/tag/v3.0.5

**Comment by DonCallisto** [comment]
Thank you!
