### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by mvar** [alexdebril/rss-atom-bundle#131]
Hey, what happened with this 3.0 version?

- Author getter is now broken (https://github.com/alexdebril/feed-io/issues/72)
- In some cases description is now returned as HTML with special chars escaped.
- In some cases URL is now returned instead of public ID.

**Comment by alexdebril** [comment]
Hi,

The author thing is now handled. Can you give me examples of feeds with the description including special chars escaped ?

Concerning the public ID, feed-io returns the URL if the feed doesn't have any public ID.

**Comment by mvar** [comment]
I will provide examples later today.

With public ID case, now I'm getting URL where I was previously getting public ID. Older version of this bundle still returns public ID on the same feed.

**Comment by alexdebril** [comment]
Could you tell me if the loss of the public ID happens with RSS or Atom feeds ?

**Comment by mvar** [comment]
RSS, if I recall correctly.

**Comment by mvar** [comment]
@alexdebril I can confirm, that public ID issue happens on RSS feeds. I have inspected few pages that has this issue and they all are powered by wordpress.

**Comment by alexdebril** [comment]
The public ID issue is related to this one : https://github.com/alexdebril/feed-io/issues/82

**Comment by alexdebril** [comment]
Hi @mvar,

I close this issue as I just opened another one the special chars : https://github.com/alexdebril/rss-atom-bundle/issues/134

Thank you for your feedback
