### ISSUE TITLE
fails on valid RSS feeds

### ISSUE THREAD

**Issue by cruiser12** [alexdebril/rss-atom-bundle#152]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.bafin.de%2FDE%2FService%2FTopNavigation%2FRSS%2F_function%2FRSS_Aufsicht.xml

**Comment by cruiser12** [comment]
its the user-agent

**Comment by alexdebril** [comment]
duplicates https://github.com/alexdebril/feed-io/issues/145
