### ISSUE TITLE
How to provide additional namespaces in xml-root-element?

### ISSUE THREAD

**Issue by KnechtRootRecht232** [alexdebril/rss-atom-bundle#175]
i try to provide a rss-feed described on MSN:
https://partnerhub.msn.com/docs/example/vcurrent

there'r many additional fields/keys and namespaces. the fields can i set with `Feed::set('key', 'value')` or `Item::set('key', 'value')`, but how to set the additional-namespaces in root-element?
```
<rss xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:mi="http://schemas.ingestion.microsoft.com/common/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    version="2.0">
```

**Comment by alexdebril** [comment]
This is a question related to feed-io, you'll find the answer is in this issue : https://github.com/alexdebril/feed-io/issues/191
