### ISSUE TITLE
if items are empty or not set its generating only end tag

### ISSUE THREAD

**Issue by cf-sahmed** [alexdebril/rss-atom-bundle#177]
for example, when no comments item set then it is generating only `<comments/>` which is invalid by w3c

**Comment by alexdebril** [comment]
Hi,

Could you run the above command in your project and paste the output please : 

```
composer show debril/rss-atom-bundle
```

**Comment by alexdebril** [comment]
```
versions : * v2.4.3
```

You're using an old version, you should consider upgrading to v4.x in which this issue is fixed.

**Comment by cf-sahmed** [comment]
Thanks
