### ISSUE TITLE
Request header wrong validation

### ISSUE THREAD

**Issue by szosa** [alexdebril/rss-atom-bundle#180]
In Controller/StreamController::setModifiedSince(), you check $request->headers->has('If-Modified-Since').
In some cases this key can exist in headers array with null value. I sugests add second condition with checking !is_null

**Comment by homarx** [comment]
I can confirm this. Found this in error log:

Type error: DateTime::createFromFormat() expects parameter 2 to be string, null given at /.../debril/rss-atom-bundle/Debril/RssAtomBundle/Request/ModifiedSince.php line 33
