### ISSUE TITLE
Undefined method getParameter in StreamController (since 4.2.2)

### ISSUE THREAD

**Issue by homarx** [alexdebril/rss-atom-bundle#185]
Since AbstractController is used in StreamController (instead of Controller) feed generating breaks with error "Undefined method getParameter in StreamController.php 159".
Even the default MockProvider doesn't work anymore.

When downgrading to v4.2.1 feed is generated as expected.

**Comment by alexdebril** [comment]
ok, thanks for the feedback.
Shortly, the `StreamController` won't call `getParameter` anymore

**Comment by alexdebril** [comment]
Which version of Symfony are you using ? Because I don't think it breaks for all versions, otherwise it would have been blocked by unit tests

**Comment by homarx** [comment]
I use Symfony version is 3.4.30

**Comment by alexdebril** [comment]
Probably fixed in 4.3, could you confirm ? 
(I mostly use Sf 4.x for my tests)

**Comment by homarx** [comment]
I upgraded to 5.0.1, adapted my custom provider and everything works!
Thanks for your work Alex

**Comment by alexdebril** [comment]
Cool, thanks for your feedback!
Speaking of the new provider, what do you think of the new interface?

**Comment by homarx** [comment]
To be honest; I only took a look at the MockProvider to see what I have to change in my custom provider getting things work : )

**Comment by alexdebril** [comment]
Well, at least it's working! 😀
Thanks again for your time, I close the issue
