### ISSUE TITLE
Deprecations raise on composer install

### ISSUE THREAD

**Issue by OskarStark** [alexdebril/rss-atom-bundle#200]
Hi I am using the latest version of `debril/rss-atom-bundle`:

>Deprecation Notice: Class Debril\RssAtomBundle\DependencyInjection\ConfigurationTest located in ./vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Tests/DependencyInjection/ConfigurationTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

>Deprecation Notice: Class Debril\RssAtomBundle\Provider\MockProviderTest located in ./vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Tests/Provider/MockProviderTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by alexdebril** [comment]
fixed by #203
