### ISSUE TITLE
Wiki out of date?

### ISSUE THREAD

**Issue by JAIC-be** [alexdebril/rss-atom-bundle#201]
Hiya,

I'm trying to have my own custom Provider class implemented but the Wiki seems to be out of date (no yaml example and the Debril\RssAtomBundle\Provider\FeedContentProviderInterface is not found).

Is there an up to date, more in depth, explanation on how to provide your own feeds?

----
Oddly when I tried the code documentation yesterday, it wasn't working (which is why I looked at the wiki today). But after the Wiki was a dead end, I looked at the docs again and got it working... Too tired yesterday I guess -_-

**Comment by alexdebril** [comment]
Hello,

You're right the wiki is out of date, however I'm glad you've finally figured it out :) 

May I ask you how did you find out ? Reading this ? https://github.com/alexdebril/rss-atom-bundle/blob/master/Provider/FeedProviderInterface.php

**Comment by JAIC-be** [comment]
Reading https://github.com/alexdebril/rss-atom-bundle#providing-feeds and https://github.com/alexdebril/rss-atom-bundle#useful-tips with a clearer head did the trick. I blame long days and lots of nights having to get up for the little ones >_<

**Comment by alexdebril** [comment]
Closing, as you've found the info you were looking for and now the Wiki is shut down
