### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by lahaxearnaud** [alexdebril/rss-atom-bundle#204]
Hello,

First of all thank you for this package.

SF 6 is out since november https://symfony.com/releases/6.0.
Did you plan to support this version of SF ?

For information, I do not have any deprecation on this packge on SF 5.4. 

Arnaud

**Comment by alexdebril** [comment]
Hello,

The bundle is to be maintained whatever the Symfony version is, so yes. Maybe there's only the need to update `composer.json` accordingly, I didn't get the opportunity to pop out a SF6 app since its release.

**Comment by alexdebril** [comment]
it's fixed, main issue was compatibility of feed-io with monolog
