### ISSUE TITLE
Error: The annotation "@Route" and "@Template"

### ISSUE THREAD

**Issue by dvdsantana** [alexdebril/rss-atom-bundle#34]
composer update fail:

[Doctrine\Common\Annotations\AnnotationException]  
  [Semantical Error] The annotation "@Route" in method Debril\RssAtomBundle\Controller\StreamController::indexAction() was never imported. Did you maybe forget to add a "use" statement for this annotation? 

and

[Doctrine\Common\Annotations\AnnotationException]  
  [Semantical Error] The annotation "@Template" in method Debril\RssAtomBundle\Controller\StreamController::indexAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?

Must add two use in StreamController:
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

**Comment by kboukhadra** [comment]
thanks a lot
