### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by garak** [alexdebril/rss-atom-bundle#43]
I would like to do some functional tests on my application (using this bundle).
My application is simply reading an external feed, then it display results
I was thinking of use a mock driver to pass to FeedReader class, but unfortunately debril.reader service is not using parameters (it has debril.http.curl directly injected).
I think this is not so fair.
For now I'll create an adapter, but it would be nice to see this fixed.

**Comment by alexdebril** [comment]
Dependency Injection now lets you replace feed-io with a mock class. Please re-open this issue if the new configuration doesn't solve your issue.
