### ISSUE TITLE
Catching exceptions and error handling

### ISSUE THREAD

**Issue by benr77** [alexdebril/rss-atom-bundle#48]
What is the best way to catch errors etc? I'm using Symfony2.

When I try and fetch a non-existent feed I get 

Warning: SimpleXMLElement::__construct(): Entity: line 11: parser error : xmlParseEntityRef: no name in /home/chaletops/dev/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/FeedReader.php line 21

Thanks

**Comment by alexdebril** [comment]
This issue is no longer accurate, I close it
