### ISSUE TITLE
Enclosure tag

### ISSUE THREAD

**Issue by mxnr** [alexdebril/rss-atom-bundle#53]
Hello Alex!
Is there any way to get content of enclosure tag from feed?

**Comment by jion** [comment]
Any news about this issue? I see the related commit but i dont understand how i can access to enclosure objects with this change.

**Comment by alexdebril** [comment]
I think I typed the wrong issue ID in my commit message, sorry.

**Comment by alexdebril** [comment]
I'm working on it, you can expect a release this month.

Cheers

Alex

**Comment by alexdebril** [comment]
It's not official yet but rss-atom-bundle now supports enclosures. Only for reading, you need to call getMedias() to fetch medias from an item. Documentation is not ready, but I will write it soon. Please tell me if the solution meets your needs.

Cheers,

Alex

**Comment by mxnr** [comment]
Awesome work, Alex, thanks a lot!
