### ISSUE TITLE
Serialization of feed items not working

### ISSUE THREAD

**Issue by JoakimLofgren** [alexdebril/rss-atom-bundle#58]
If I try to store the result from `$feed->getItems()` in a `Doctrine\Common\Cache\ApcCache` I get the following error:

> Serialization of 'SimpleXMLElement' is not allowed

This seems to be because the `Debril\RssAtomBundle\Protocol\Parser\Item` fields are SimpleXMLElement and not string as the phpdoc denotes.

Seems like the RSS and Atom parsers need to cast to string before calling the setters.

I tried this using version 1.4.2 as I haven't upgraded to Symfony 2.6 yet.

**Comment by alexdebril** [comment]
I pushed a fix on 1.4.x and 1.5.x branches, let me know if you still have the problem.

**Comment by JoakimLofgren** [comment]
It fixed everything except the additional namespaces thing, I still need to do:
```php    
    $newItems = $feed->getItems();
    array_walk(
        $newItems,
        function (&$item) {
            /*$item->setComment(strval($item->getComment()));
            $item->setAuthor(strval($item->getAuthor()));
            $item->setLink(strval($item->getLink()));
            $item->setSummary(strval($item->getSummary()));
            $item->setDescription(strval($item->getDescription()));
            $item->setPublicid(strval($item->getPublicid()));
            $item->setTitle(strval($item->getTitle()));
            */
            foreach ($item->getAdditional() as &$additional) {
                $additional = strval($additional);
            }
        }
    );
```

To be able to serialize the feed items.

Although I don't know if you can safely convert every additional value to string..

**Comment by iveretelnyk** [comment]
I'm using v2.4.2 and still have this problem.
