### ISSUE TITLE
Additional field

### ISSUE THREAD

**Issue by waldemarnt** [alexdebril/rss-atom-bundle#60]
Hello guys, i'm using your bundle, is a good bundle.
But in my XML have a different field named "image", have a way to parse this field without  change the bundle code?
Tnx!

**Comment by alexdebril** [comment]
Hi,

Thanks for your feedback. Usually images are embedded in enclosure nodes, which is not yet implemented in rss-atom-bundle.

You need to extend rss-atom-bundle's parsers to handle image tags, as every tag names are hard coded.

Cheers,

Alex

**Comment by waldemarnt** [comment]
Hey mate.
Tnx for your feedback, was it i did.
I think dont have a dynamic way to handle this additional fields, the unique way is it that happens, we need create a own parser to handle, but this works fine.

Hugs!
