### ISSUE TITLE
getMedias() items always have empty URL

### ISSUE THREAD

**Issue by alexmatveev** [alexdebril/rss-atom-bundle#67]
Hello!
Please tell me, am I using this bundle a wrong way?
Because it does not parse URL from this feed http://ria.ru/export/rss2/index.xml
```
<enclosure url="http://cdn14.img22.ria.ru/images/43313/87/433138710.jpg" type="image/jpeg" length="26331"/>
```
Using this code:
```
$medias = $item->getMedias();
foreach ( $medias as $media ) {
var_dump($media->getUrl());
}
```
Medias array is filled by items with empty URLs

**Comment by alexdebril** [comment]
Hello!

The problem comes from the bundle not your code. I fixed it, you should get a correct URL now.

Cheers,

Alex

**Comment by alexmatveev** [comment]
@alexdebril Thanks, I see new attrs support added, it works now!
