### ISSUE TITLE
Supports routing

### ISSUE THREAD

**Issue by romaricdrigon** [alexdebril/rss-atom-bundle#69]
Hi,

It would be really neat to be able to give a route in place of an URL in `ItemOutInterface::getLink`.
Such result can be achieved through a Custom `FeedProvider` I understand, but it is so common having it included could be nice.

About implementation, the best way IMO is to have  a `RoutedItemOutInterface`, where `getLink` returns route and parameters.

**Comment by alexdebril** [comment]
Hi,

It's a good idea, I'll code this during the next weeks. 

Cheers,
