### ISSUE TITLE
Not able to understand the purpose of readFeed()

### ISSUE THREAD

**Issue by shairyar** [alexdebril/rss-atom-bundle#77]
Hi,

I can get the feeds i want to fetch using 
<pre>
$feed = $reader->getFeedContent($url, $date);
</pre>

however I dont undetstand the purpose of readFeed(), i read the documentation but i still dont understand the purpose of it, what do you mean by

readFeed() is designed to hydrate an object you pass as an argument.

and then in the example you mentioned

<pre> 
// create your own Feed
$feed = new Acme\Feed; 
</pre>

Once I have the feeds i need, where does readFeed() comes into play and why will i need it?

**Comment by alexdebril** [comment]
Let's say you have your own Feed class and you don't want to use the one provided by rss-atom-bundle.

This class could be AppBundle\Entity\Feed and would be like this : 

```php

namespace AppBundle\Entity;

use Debril\RssAtomBundle\Protocol\FeedInterface

class Feed implements FeedInterface
{
    // implement here all FeedInterface methods
}

```

Now you can call readFeed() to fill your own object with the feed's content : 

```php

$feed = new AppBundle\Entity\Feed;
$feedReader->readFeed($url, $feed, $modifiedSince);

```

I hope this explanation helps.

**Comment by shairyar** [comment]
Thanks. Si it is meant to add feeds into databas.

**Comment by shairyar** [comment]
Should this code be inside a loop so all items get added to database ?

<code>
$feedReader->readFeed($url, $feed, $modifiedSince);
</code>

**Comment by shairyar** [comment]
I want to use the class that came with rss-atom-bundle to add feeds to database how do I do that?

**Comment by alexdebril** [comment]
I think you should map rss-atom-bundle class in doctrine mapping using YAML configuration like explained in this documentation : http://doctrine-orm.readthedocs.org/en/latest/reference/yaml-mapping.html
