### ISSUE TITLE
Unable to insert fetched feeds into database

### ISSUE THREAD

**Issue by SadiaK** [alexdebril/rss-atom-bundle#78]
After reading the instructions I can get the RSS feeds however I am not able to insert them into database.

This is the controller I have that fetches the feeds and then should insert into database
<pre>
<code>
namespace AppBundle\Controller;

use AppBundle\Entity\Feed as Feed;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        // fetch the FeedReader
        $reader = $this->container->get('debril.reader');

        // this date is used to fetch only the latest items
        $unmodifiedSince = '11/11/2014';
        $date = new \DateTime($unmodifiedSince);

        // the feed you want to read
        $url = 'https://example.com/feed/';

        // now fetch its (fresh) content
        $feed = $reader->getFeedContent($url, $date);
        // in developer tool bar I can see the feeds using dump()
        dump($feed);

        $items = $feed->getItems();

        //Insert fetched feeds into database
        $feeds = new Feed;
        $reader->readFeed($url, $feeds, $date);
        return $this->render('default/index.html.twig');
    }

}
</code>
</pre>

I do not see any error and I do not see any feeds inside my database table as well.

This is my Feed Entity
<pre>
<code>
namespace AppBundle\Entity;

use Debril\RssAtomBundle\Protocol\FeedInterface;
use Debril\RssAtomBundle\Protocol\ItemIn;
use Doctrine\ORM\Mapping as ORM;

/**
 * Feed
 */
class Feed implements FeedInterface
{
    /**
     * @var integer
     */
    private $id;
    private $lastModified;
    private $title;
    private $description;
    private $link;
    private $publicId;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Atom : feed.entry <feed><entry>
     * Rss  : rss.channel.item <rss><channel><item>
     * @param \Debril\RssAtomBundle\Protocol\ItemIn $item
     */
    public function addItem(ItemIn $item)
    {
        // TODO: Implement addItem() method.
    }

      public function setLastModified(\DateTime $lastModified)
    {
        $this->lastModified = $lastModified;

        return $this;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    public function setPublicId($id)
    {
        $this->publicId = $id;

        return $this;
    }

    /**
     * Atom : feed.updated <feed><updated>
     * Rss  : rss.channel.lastBuildDate <rss><channel><lastBuildDate>
     * @return \DateTime
     */
    public function getLastModified()
    {
        return $this->lastModified;
    }

    /**
     * Atom : feed.title <feed><title>
     * Rss  : rss.channel.title <rss><channel><title>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Atom : feed.subtitle <feed><subtitle>
     * Rss  : rss.channel.description <rss><channel><description>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Atom : feed.link <feed><link>
     * Rss  : rss.channel.link <rss><channel><link>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Atom : feed.id <feed><id>
     * Rss  : rss.channel.id <rss><channel><id>
     * @return string
     */
    public function getPublicId()
    {
        return $this->publicId;
    }

    /**
     * Atom : feed.entry <feed><entry>
     * Rss  : rss.channel.item <rss><channel><item>
     * @return array[\Debril\RssAtomBundle\Protocol\ItemOut]
     */
    public function getItems()
    {
        // TODO: Implement getItems() method.
    }
}
</code>
</pre>

What am I doing wrong?

**Comment by SadiaK** [comment]
You also mention the following statement at https://github.com/alexdebril/rss-atom-bundle/wiki/Reading-feeds#using-readfeed 

The $feed object is then filled with Item instances. If you want to use your own class instead of Item, just edit your services.xml and add a new parameter :

at i am puzzled how it is done? am i suppose to define a service because i do not see doctrine being called anywhere to add fetched feeds in database and linking the variable $feed with Item instances.

**Comment by alexdebril** [comment]
HI,

rss-atom-bundle doesn't explicitely calls Doctrine while reading, it builds a Feed and thren it's yours to store it in database.

I made a test project, look at https://bitbucket.org/adebril/feed-aggregator-bundle/src/781c4fc004a4ce9feb89db30aaf5ae4d827c3480/Command/AbstractCommand.php?at=master#cl-35

the command gets a Feed instance from the Reader and then use the FeedRepository to save it : https://bitbucket.org/adebril/feed-aggregator-bundle/src/781c4fc004a4ce9feb89db30aaf5ae4d827c3480/Entity/FeedRepository.php?at=master#cl-100

In feed-aggregator-bundle I used custom Feed and Item classes to handle the link in database and I referenced them in the bundle's service parameters : https://bitbucket.org/adebril/feed-aggregator-bundle/src/781c4fc004a4ce9feb89db30aaf5ae4d827c3480/Resources/config/services.xml?at=master

I hope those code samples will help.

Cheers

**Comment by SadiaK** [comment]
I cant view the links you shared, i see the error  Access denied

**Comment by alexdebril** [comment]
Sorry, the repository was private I just made it public
