### ISSUE TITLE
classNotFoundInNamespaces exception

### ISSUE THREAD

**Issue by shairyar** [alexdebril/rss-atom-bundle#88]
Hi,

I am able to get the feeds I want and I can see them in `dump($items)` but when I try to persist them I get the following error and I am clueless why is this appearing.
<pre>
<code>
The class 'Debril\RssAtomBundle\Protocol\Parser\Item' was not found in the chain configured namespaces Symfony\Bundle\AsseticBundle\Entity, AppBundle\Entity`
</code>
</pre>

This is my `Controller`
<pre><code>
        $em = $this->getDoctrine()->getManager();
        // fetch the FeedReader
        $reader = $this->container->get('debril.reader');

        // this date is used to fetch only the latest items
        $unmodifiedSince = '01/01/2000';
        $date = new \DateTime($unmodifiedSince);

        // the feed you want to read
        $url = 'http://xyz.com/feed/';

        $feeds = $reader->getFeedContent($url, $date);
        $items = $feeds->getItems();

        dump($items);
        foreach ( $items as $item ) {
            $em->persist($item);
        }
        $em->flush();
</code>
</pre>

I did `implement` `FeedInterface` to my `Feed` Entity and `ItemInInterface, ItemOutInterface` to my `Item` Entity

This is what my `orm.yml` looks like for `Feed` and `Item` Entity

Feed
<pre>
<code>
AppBundle\Entity\Feed:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        link:
            type: text
        publicId:
            type: text
        lastModified:
            type: datetime
        lastViewed:
            type: datetime
    oneToMany:
        items:
            targetEntity: AppBundle\Entity\Item
            mappedBy: feed
            cascade: ["persist"]
    lifecycleCallbacks: {  }
</code>
</pre>

Item
<pre>
<code>
AppBundle\Entity\Item:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        title:
            type: text
            nullable: true
        summary:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        medias:
            type: text
            nullable: true
        updated:
            type: string
            nullable: true
        publicId:
            type: string
            nullable: true
        link:
            type: string
            nullable: true
        comment:
            type: string
            nullable: true
        author:
            type: string
            nullable: true
    manyToOne:
        feed:
            targetEntity: AppBundle\Entity\Feed
            inversedBy: items
            joinColumn:
                name: feed_id
                referencedColumnName: id
</code>
</pre>

Any help will be really appreciated as I am clueless why i am getting the error?

**Comment by alexdebril** [comment]
Hi,

Sorry I didn't saw this issue before, did you manage to fix it since it happened ?

I guess a 'use' statement must me missing somewhere

**Comment by alexdebril** [comment]
I guess you manage to solve the bug, I close the issue
