### ISSUE TITLE
Extract XML parsing from FeedReader

### ISSUE THREAD

**Issue by romaricdrigon** [alexdebril/rss-atom-bundle#92]
Hi,

At the moment, XML parsing is done in `FeedReader`:
```php
    public function parseBody(HttpDriverResponse $response, FeedInInterface $feed, array $filters = array())
    {
        if ($response->getHttpCodeIsOk()
            || $response->getHttpCodeIsRedirection()) {
            $xmlBody = new SimpleXMLElement($response->getBody());
            $parser = $this->getAccurateParser($xmlBody);

            return $parser->parse($xmlBody, $feed, $filters);
        }
...
```

The idea would be to introduce a `XMLParser` service, to decouple those 2 aspects. Then users could only override that one, as you would override the HTTP fetcher.
Real life use case is when you want to adapt to malformed XML (typically some WordPress plugins add blank lines before... those are accepted by most RSS aggregators).

Please just validate the idea and I will work on the PR :)

**Comment by alexdebril** [comment]
Hi, 

Thank you very much, this is a good idea. Yes,  you can work on it :-) 

Cheers,

**Comment by romaricdrigon** [comment]
I'm closing the issue in favor of the PR!
