### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by mxnr** [alexdebril/rss-atom-bundle#96]
Hello Alex!
Do you plain to update `rss-atom-bundle` or `feed-io` to support Symfony 3?
I tried to change components version on my fork of `rss-atom-bundle` to 3.0, all unit tests are green. Not sure about functionality:)

**Comment by alexdebril** [comment]
Hi,

I'm working on feedio-bundle to support Symfony 3.0. I'll perform some tests on rss-atom-bundle to state if it is really compatible, but I think it is because rss-atom-bundle doesn't have any form.

If you are starting from scratch, I encourage you to use feedio-bundle.

**Comment by alexdebril** [comment]
Hi,

feed-io-bundle and rss-atom-bundle are now both compatible with Symfony 3.0.

**Comment by mxnr** [comment]
Cool, thanks Alex!
